### ISSUE TITLE
Hard crash when loading a song

### ISSUE THREAD

**Issue by Kashouryo** [LumpBloom7/sentakki#47]
version: d98119c
the game will hard crash when loading any song for play. probably due to map conversion.

**Comment by LumpBloom7** [comment]
Apologies, but I can't repro this on my end (using lazer 2020.515.0). Can I get a runtime log(located in `%appdata%/logs`)?

**Comment by Kashouryo** [comment]
Here's the log file that contains the error:
https://pastebin.com/q8ysVb6w

**Comment by LumpBloom7** [comment]
Looks like a crash related to the skinnablesound used by break notes.

Can you try on the default lazer skin?

EDIT: Found the potential cause of the problem, will test to verify.

**Comment by Kashouryo** [comment]
Nope, the problem still exists. However, I did remember that ppy recently changed how some of the skinnable sounds work.
https://github.com/ppy/osu/pull/9068

**Comment by LumpBloom7** [comment]
Possibly, especially if you are running this on the latest master, rather than the release.

The change might have made my silent mistake come to light. 
Namely the lack of a null conditional on this line:
https://github.com/LumpBloom7/sentakki/blob/d98119c1cc21cc0ea08141bb99bf88ddc492b2e9/osu.Game.Rulesets.Sentakki/Objects/Drawables/DrawableBreak.cs#L26

**Comment by LumpBloom7** [comment]
Okay just tested the latest sentakki release against lazer@master, and it seems to work without issue.

**Comment by LumpBloom7** [comment]
Okay, crash confirmed with latest master

**Comment by LumpBloom7** [comment]
The crash seems to be caused by a change made in osu that slightly changes the way adjustments are made.

Blocked: Waiting for an updated osu dependency package.
